### ISSUE TITLE
Atualização do readme.

### ISSUE THREAD

**Issue by fvieir** [tascintra/nft-preview-card#1]
Ola Tiago, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minhas solicitação para atualização do readme.

Seu readme ficou muito bom, mas para contribuir para seu crescimento, vejo que pode ter algumas melhorias, tais como, detalhes do projeto, o que você aprendeu com ele, quais foram as dificuldades. Mas se sinta livre para adicionar mais coisas.

Qualquer duvida é so chamar.

Forte abraço.

**Comment by tascintra** [comment]
Olá Fabrício, por aqui tudo jóia.

Obrigado pelo feedback. Fiz a remodelagem do readme to projeto e defini o modelo para seguir nos próximos projetos.

Atenciosamente,
Tiago

**Comment by fvieir** [comment]
Ficou muito bom. Parabéns.
